### ISSUE TITLE
Bindings a broken after calling this.render()

### ISSUE THREAD

**Issue by ThatScalaGuy** [slimjs/slim.js#62]
I created a fiddle to show an error (or misunderstanding on my side :)).
After pressing the update button, which only calls `this.render()` I got following exception `Cannot read property 'chain' of undefined`.

Is that an issue or is it not intended to call `render()` within the component?  

https://jsfiddle.net/wmoL2v81/66/   (I know the binding will be updated after the value is changed. In my real component, there is some logic in the onRender() method. That's the reason I thought calling this.render() is a smart idea :) )

**Comment by eavichay** [comment]
@ThatScalaGuy Thanks.
Basically this error should not happen. I will look into it.

Calling render should be done carefully. If your data has changed the binding should update your DOM tree. Render is used for providing a new template instead of the current one, for example
```js
update () {
  this.render('<h1>Hello</h1>')
}
```
This will replace your default template with a new one and run the binding process from scratch. As said, there is possibly a bug and I will look into it as soon as possible.

If your component has more than one possible view, depends on your data, you could use s:switch and s:if as conditional rendering.

Perhaps you could share more about the real use-case.
